```{r libraries}
library(flip)
library(resamplingMCP)
library(ggplot2)
library(reshape2)
library(dplyr)
library(magrittr)
```

```{r t vs permutatio test}

adaptive_ttest <- function(x){
    n <- length(x)
    n1 <- floor(n/2)
    p1 <- t.test(x[1:n1],alternative='greater')$p.value
    p2 <- t.test(x[(n1+1):n],alternative='greater')$p.value
    {sqrt(c(n1,n-n1)/n) * qnorm(c(p1,p2),lower=F)} %>% sum() %>% pnorm(lower=FALSE)
}

hetero_ttest <- function(x,s=2){
    n <- length(x)
    if(n %% s != 0) stop('Sample size has to be even')
    n1 <- floor(n/s)
    xs <- split(x,rep(1:s,each=n1))
    ps <- sapply(lapply(xs,t.test,alternative='greater'),`[[`,'p.value')
    {sqrt(n1/n) * qnorm(ps,lower=F)} %>% sum() %>% pnorm(lower=FALSE)
}

compare_tvsp <- function(n,B,alpha=.05,rdist=rnorm_hetero,...) {
    out <- sapply(1:B,function(i,n=n,...) {
        x <- rdist(n,...)
        c(power_ttest = t.test(x,alternative='greater')$p.value,
          power_ptest = flip(x,tail=1)@res$`p-value`,
          power_atest = hetero_ttest(x,s=10))
    },n=n,...)
    rowMeans(out<=alpha)
}

plist <- lapply(seq(0,5,.25),function(ncp) c(ncp=ncp,compare_tvsp(20,5000,ncp=ncp,df=1)))

power_comparison <- plist %>%
    do.call(what='rbind') %>%
        as.data.frame %>%
            melt(id.vars="ncp",variable.name='test',value.name='power')

pdf("/tmp/permutation_vs_ttest_hetero.pdf",width=7,height=4)
qplot(ncp,power,linetype=test,data=power_comparison,geom='line')
dev.off()

plist2 <- lapply(seq(0,5,.25),function(ncp) c(ncp=ncp,compare_tvsp(20,5000,rdist=rt,ncp=ncp,df=1)))

power_comparison <- plist2 %>%
    do.call(what='rbind') %>%
        as.data.frame %>%
            melt(id.vars="ncp",variable.name='test',value.name='power')

pdf("/tmp/permutation_vs_ttest_tdist.pdf",width=7,height=4)
qplot(ncp,power,linetype=test,data=power_comparison,geom='line')
dev.off()

power_diff <- mutate(dcast(power_comparison,ncp~test),power_diff=power_ptest - power_ttest,power_rel=power_ptest/power_ttest-1)
qplot(ncp,power_diff,data=power_diff,geom='line')

out <- replicate(10000,adaptive_ttest(rt(10,df=1,ncp=1)))
out2 <- replicate(10000,flip(rt(10,df=1,ncp=1),alternative=1)@res$`p-value`)
out3 <- replicate(10000,hetero_ttest(rt(10,df=1,ncp=1),s=2))
out4 <- replicate(10000,hetero_ttest(rt(10,df=1,ncp=1),s=5))
mean(out < .05)
mean(out2 < .05)
mean(out3 < .05)
mean(out4 < .05)


```


## Simulations under the null

### Conditional both

```{r adaptive null}
## Small sample
simulate_trials(1,4,8)
simulate_trials(1,6,12)

## Medium sample
simulate_trials(1,20,40)
simulate_trials(1,50,100)

## Large sample
simulate_trials(1,100,200)
simulate_trials(1,200,400)

```
### Conditional first

```{r adaptive null}
## Small sample
simulate_trials(1,4,8)
simulate_trials(1,6,12)

## Medium sample
simulate_trials(1,20,40)
simulate_trials(1,50,100)

## Large sample
simulate_trials(1,100,200)
simulate_trials(1,200,400)

```

## Conditional none

```{r adaptive null}
## Small sample
simulate_trials(1,4,8)
simulate_trials(1,6,12)

## Medium sample
simulate_trials(1,20,40)
simulate_trials(1,50,100)

## Large sample
simulate_trials(1,100,200)
simulate_trials(1,200,400)

```


```{r simple example}
x1 <- rnorm(12)/sqrt(2)
x2 <- rnorm(12)/sqrt(2)
g1 <- rep(0:1,each=6)
g2 <- rep(0:1,each=6)
x1 <- x1+g1
tstat(x1,g1)

z_test(x1,NULL,g1,NULL)
t_test(x1,NULL,g1,NULL)

o <- omega(g1,B=10)
sumdiff(x1,o)
meandiff(x1,o)
zstat(c(x1,x2),c(g1,g2))
tstat(c(x1,x2),c(g1,g2))
tstat(c(x1,x2),c(g1,g2))


normal_CER(x1,g1,length(x1)+length(x2))
t_CER(x1,g1,length(x1)+length(x2),)
boxplot(cbind(resamplingMCP:::perm_dist(x1,x2,g1,g2,meandiff,100),
              resamplingMCP:::cond_dist(x1,x2,g1,g2,meandiff,100)))
permutation_CER(x1,g1,x2,meandiff,B=10000)


```

```{r}
library(resamplingMCP)
library(parallel)
MCMC = 1000
B = 1000
options(mc.cores=min(detectCores()-1,30))

## Medium size trial
n  <- 12
n1 <- 6



## Type 1 error of design where second stage is as preplanned
## to run a 1 sample symulation, just
T1_preplanned <- type1(rcauchy,n=n,n1=n1,B=B,MCMC=MCMC,stat=meandiff)
colMeans(T1_preplanned)

# colMeans(T1_preplanned)
# ## Type 1 error of normal distribution CER
# T1_normal <- type1_normal_preplanned(n,n1,MCMC)
# colMeans(T1_normal)


## Type 1 error of design where second stage is as preplanned
# to run a 1 sample symulation, just
T1_preplanned <- type1_preplanned(n,n1,B,MCMC,one_sample=TRUE)
colMeans(T1_preplanned)
# preplanned influenced     normal 
# 0.00000000 0.00000000 0.02479908 


## Type 1 error of normal distribution CER
T1_normal <- type1_normal_preplanned(n,n1,MCMC,one_sample=TRUE)
colMeans(T1_normal)
# preplanned influenced 
# 0.02669741 0.02669741 

## Type 1 error of design where second stage is as preplanned, heteroscedastic errors

T1_preplanned_hetero <- type1_preplanned_hetero(n,n1,B,MCMC,one_sample=TRUE)
colMeans(T1_preplanned_hetero)
# preplanned influenced     normal 
# 0.0317010  0.0313780  0.3103739 


## Type 1 error of normal distribution CER, heteroscedastic errors
MCMC = 5000
B = 5000
T1_normal_hetero <- type1_normal_preplanned_hetero(n,n1,MCMC,B,one_sample=TRUE)
colMeans(T1_normal_hetero) 
# preplanned influenced 
# 0.2367942  0.2367942 

T1_tstat_hetero <- type1_tstat_hetero(n,n1,MCMC,one_sample=FALSE)
colMeans(T1_tstat_hetero)

# preplanned influenced 
# 0.2367942  0.2367942 




```
