// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// random_reassignments_cpp
IntegerMatrix random_reassignments_cpp(const IntegerVector g, const int nperm);
RcppExport SEXP resamplingMCP_random_reassignments_cpp(SEXP gSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const IntegerVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< const int >::type nperm(npermSEXP);
    __result = Rcpp::wrap(random_reassignments_cpp(g, nperm));
    return __result;
END_RCPP
}
