// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sumdiffC
NumericVector sumdiffC(NumericVector x, IntegerMatrix g);
RcppExport SEXP resamplingMCP_sumdiffC(SEXP xSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type g(gSEXP);
    __result = Rcpp::wrap(sumdiffC(x, g));
    return __result;
END_RCPP
}
// meandiffC
NumericVector meandiffC(NumericVector x, IntegerMatrix g);
RcppExport SEXP resamplingMCP_meandiffC(SEXP xSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type g(gSEXP);
    __result = Rcpp::wrap(meandiffC(x, g));
    return __result;
END_RCPP
}
// random_reassignments_cpp
IntegerMatrix random_reassignments_cpp(const IntegerVector g, const int nperm);
RcppExport SEXP resamplingMCP_random_reassignments_cpp(SEXP gSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const IntegerVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< const int >::type nperm(npermSEXP);
    __result = Rcpp::wrap(random_reassignments_cpp(g, nperm));
    return __result;
END_RCPP
}
