# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_reassignments_cpp <- function(g, nperm = 1000L) {
    .Call('resamplingMCP_random_reassignments_cpp', PACKAGE = 'resamplingMCP', g, nperm)
}

