# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sumdiffC <- function(x, g) {
    .Call('resamplingMCP_sumdiffC', PACKAGE = 'resamplingMCP', x, g)
}

meandiffC <- function(x, g) {
    .Call('resamplingMCP_meandiffC', PACKAGE = 'resamplingMCP', x, g)
}

random_reassignments_cpp <- function(g, nperm = 1000L) {
    .Call('resamplingMCP_random_reassignments_cpp', PACKAGE = 'resamplingMCP', g, nperm)
}

random_samples_cpp <- function(xs, k, nsam = 1000L) {
    .Call('resamplingMCP_random_samples_cpp', PACKAGE = 'resamplingMCP', xs, k, nsam)
}

